### PR TITLE
check if defined already

### PR DESCRIPTION
**Pull request by swiffer**
PHP throws Notices when running the testsuite otherwise

### CODE REVIEW

**Comment by mirko-pagliai** [comment]
`define()` can take an array as value only starting with PHP 7:
http://php.net/manual/en/function.define.php

**Comment by swiffer** [comment]
ok, see that. got notices of already defined after upgrading to 3.6.0-beta1. was some duplicate bootstrapping involved there that has been fixed in 3.6.0-beta2 already

**Comment by swiffer** [comment]
ok, not solved - markstory posted a guide on what to do in cakephp/cakephp#11815

**Comment by mirko-pagliai** [comment]
I created the [cakephp3.6](https://github.com/mirko-pagliai/cakephp-database-backup/tree/cakephp3.6) branch. However, I do not receive any Notice. How do you get them?

**Comment by mirko-pagliai** [comment]
Removed `cakephp3.6` branch.

@swiffer try the `develop` branch it should now work with 3.5 and 3.6 branches.  
Let me know if it's ok, so I'll release a new version.

**Comment by swiffer** [comment]
@mirko-pagliai changes in #24 work as aspected!

**Pull request closed without merging**
